name: "Sample React CI Pipeline / workflow"

on:
    push:
        branches:
            - main
            - VD

jobs:
    bulid-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: "Setup Node JS"
              uses: actions/setup-node@v3
              with:
                node-version: "20"

            - name: "Chack node version"
              run: node --version

            - name: "Clone the repository"
              uses: actions/checkout@v2

            - name: "Installing Dependencies"
              run: npm install
            
            - name: "List directories"
              run: ls

            - name: "Run tests"
              run: npm test

            - name: "Run build"
              run: npm run build
            
            - name: "List directories"
              run: ls